logging.level:
  org.springframework: INFO

spring:
  application.name: notification-listener
  profiles.active: local
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: pt.itsector.notification.mappers.AvroSerializer
      topic-name: notification-service

---

spring:
  profiles: dev
  kafka:
    bootstrap-servers: kafka:29092