logging.level:
  org.springframework: INFO

spring:
  application.name: notification-listener
  profiles.active: local
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      topic-name: notification-service
    properties:
      schema.registry.url: http://localhost:8081
---

spring:
  profiles: dev
  kafka:
    bootstrap-servers: kafka:29092