logging.level:
  org.springframework: INFO

spring:
  application.name: notification-db-service
  profiles.active: local
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: notification-db-consumer-group
      topic-name: notification-service
      result-topic-name: notification-result-service
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/notifications_db
    username: mysql_user
    password: mysql_password
  thymeleaf:
    enabled: true
    cache: false
    mode: HTML

server:
  port : 8082

---

spring:
  profiles: dev
  kafka:
    bootstrap-servers: kafka:29092
  datasource:
    url: jdbc:mysql://db:3306/notifications_db