logging.level:
  org.springframework: INFO

spring:
  application.name: notification-dispatcher
  profiles.active: local
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: pt.itsector.notification.mappers.AvroDeserializer
      group-id: notification-consumer-group
      topic-name: notification-service
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: pt.itsector.notification.mappers.AvroSerializer
      topic-name: notification-result-service

---

spring:
  profiles: dev
  kafka:
    bootstrap-servers: kafka:29092